#!/bin/bash
# CATCHING BARRELS - Quick Production Deployment
# Optimized for Railway.app, Render.com, or Heroku

echo "╔══════════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                              ║"
echo "║              🚀 CATCHING BARRELS - PRODUCTION DEPLOYMENT 🚀                  ║"
echo "║                                                                              ║"
echo "╚══════════════════════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}📋 DEPLOYMENT OPTIONS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Choose your deployment platform:"
echo ""
echo "  1) Railway.app       (Recommended - Automatic, Free tier)"
echo "  2) Render.com        (Free tier available)"
echo "  3) Heroku            (Paid)"
echo "  4) Manual Server     (VPS/AWS/GCP/Azure)"
echo "  5) Docker            (Containerized)"
echo ""
read -p "Enter choice (1-5): " choice

case $choice in
    1)
        echo ""
        echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e "${GREEN}🚂 RAILWAY.APP DEPLOYMENT${NC}"
        echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo ""
        echo "Step 1: Install Railway CLI"
        echo "  $ npm install -g @railway/cli"
        echo ""
        echo "Step 2: Login to Railway"
        echo "  $ railway login"
        echo ""
        echo "Step 3: Initialize project"
        echo "  $ railway init"
        echo ""
        echo "Step 4: Set environment variables"
        echo "  $ railway variables set WHOP_API_KEY=your_key_here"
        echo "  $ railway variables set WHOP_COMPANY_ID=biz_4f4wiRWwiEZflF"
        echo "  $ railway variables set PORT=8000"
        echo ""
        echo "Step 5: Deploy"
        echo "  $ railway up"
        echo ""
        echo "Step 6: Get your URL"
        echo "  $ railway domain"
        echo ""
        echo -e "${GREEN}✓ Railway will auto-detect Python and install dependencies${NC}"
        echo ""
        ;;
    
    2)
        echo ""
        echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e "${GREEN}🎨 RENDER.COM DEPLOYMENT${NC}"
        echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo ""
        echo "Step 1: Create new Web Service on Render.com"
        echo "  • Connect your GitHub repo: THScoach/reboot-motion-backend"
        echo "  • Runtime: Python 3"
        echo "  • Build Command: pip install -r requirements.txt"
        echo "  • Start Command: uvicorn coach_rick_wap_integration:app --host 0.0.0.0 --port \$PORT"
        echo ""
        echo "Step 2: Add environment variables in Render dashboard"
        echo "  • WHOP_API_KEY"
        echo "  • WHOP_COMPANY_ID"
        echo ""
        echo "Step 3: Deploy"
        echo "  • Click 'Manual Deploy' or enable auto-deploy"
        echo ""
        echo -e "${GREEN}✓ Render provides free SSL and custom domains${NC}"
        echo ""
        ;;
    
    3)
        echo ""
        echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e "${GREEN}💜 HEROKU DEPLOYMENT${NC}"
        echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo ""
        echo "Step 1: Install Heroku CLI"
        echo "  $ curl https://cli-assets.heroku.com/install.sh | sh"
        echo ""
        echo "Step 2: Login"
        echo "  $ heroku login"
        echo ""
        echo "Step 3: Create app"
        echo "  $ heroku create catching-barrels-api"
        echo ""
        echo "Step 4: Set environment variables"
        echo "  $ heroku config:set WHOP_API_KEY=your_key_here"
        echo "  $ heroku config:set WHOP_COMPANY_ID=biz_4f4wiRWwiEZflF"
        echo ""
        echo "Step 5: Create Procfile (if not exists)"
        echo "  web: uvicorn coach_rick_wap_integration:app --host 0.0.0.0 --port \$PORT"
        echo ""
        echo "Step 6: Deploy"
        echo "  $ git push heroku main"
        echo ""
        echo -e "${GREEN}✓ Heroku provides free SSL certificates${NC}"
        echo ""
        ;;
    
    4)
        echo ""
        echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e "${GREEN}🖥️  MANUAL SERVER DEPLOYMENT${NC}"
        echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo ""
        echo "Step 1: SSH to your server"
        echo "  $ ssh user@your-server.com"
        echo ""
        echo "Step 2: Clone repository"
        echo "  $ git clone https://github.com/THScoach/reboot-motion-backend.git"
        echo "  $ cd reboot-motion-backend"
        echo ""
        echo "Step 3: Install dependencies"
        echo "  $ python3 -m venv venv"
        echo "  $ source venv/bin/activate"
        echo "  $ pip install -r requirements.txt"
        echo ""
        echo "Step 4: Set environment variables"
        echo "  $ export WHOP_API_KEY='your_key_here'"
        echo "  $ export WHOP_COMPANY_ID='biz_4f4wiRWwiEZflF'"
        echo ""
        echo "Step 5: Run with supervisor/systemd"
        echo "  $ sudo systemctl start catching-barrels"
        echo ""
        echo "Step 6: Configure nginx reverse proxy"
        echo "  location / {"
        echo "    proxy_pass http://localhost:8006;"
        echo "    proxy_set_header Host \$host;"
        echo "  }"
        echo ""
        echo -e "${GREEN}✓ Don't forget to configure SSL with Let's Encrypt${NC}"
        echo ""
        ;;
    
    5)
        echo ""
        echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e "${GREEN}🐳 DOCKER DEPLOYMENT${NC}"
        echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo ""
        echo "Step 1: Build Docker image"
        echo "  $ docker build -t catching-barrels ."
        echo ""
        echo "Step 2: Run container"
        echo "  $ docker run -d -p 8006:8006 \\"
        echo "    -e WHOP_API_KEY=your_key_here \\"
        echo "    -e WHOP_COMPANY_ID=biz_4f4wiRWwiEZflF \\"
        echo "    catching-barrels"
        echo ""
        echo "Step 3: Or use docker-compose"
        echo "  $ docker-compose up -d"
        echo ""
        echo -e "${GREEN}✓ Container includes all dependencies${NC}"
        echo ""
        ;;
    
    *)
        echo -e "${RED}Invalid choice${NC}"
        exit 1
        ;;
esac

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}⚙️  POST-DEPLOYMENT CONFIGURATION${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "1. Configure Whop Webhook"
echo "   • Go to: https://whop.com/biz/developer"
echo "   • Set webhook URL: https://your-domain.com/webhooks/whop"
echo "   • Enable events: membership.*, payment.*"
echo ""
echo "2. Test endpoints"
echo "   $ curl https://your-domain.com/health"
echo "   $ curl https://your-domain.com/api/swing-dna/health"
echo ""
echo "3. Update frontend API URL"
echo "   • Point frontend to: https://your-domain.com"
echo ""
echo "4. Monitor logs"
echo "   • Check application logs for errors"
echo "   • Monitor webhook deliveries"
echo ""

echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ DEPLOYMENT GUIDE COMPLETE${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "📚 Documentation: SYSTEM_TEST_REPORT.md"
echo "🔗 GitHub: https://github.com/THScoach/reboot-motion-backend"
echo "📦 Latest Commit: 7d5f133"
echo ""
echo "🎉 Ready to deploy! Choose your platform and follow the steps above."
echo ""
